name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: |
        Set-Content authtoken.txt "1uIucCxbz64rQdSpNbeuLVEIfJw_3V6kPRFzddFGoxoRUyowD" #enter your ngrok authtoken from https://dashboard.ngrok.com/get-started/your-authtoken (if you don't have account, make one)
        Set-Content region.txt "JP" #enter region for the Ngrok servers (available: EU, US, JP, AP, SA) write one of them with capital letters
   - run: |
        $region = Get-Content region.txt
        Invoke-WebRequest https://raw.githubusercontent.com/bEmcho-cyber/files/main/NGROK-$region.bat -Outfile NGROK-$region.bat
        Invoke-WebRequest https://raw.githubusercontent.com/bEmcho-cyber/files/main/NGROK-CHECK.bat -Outfile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/bEmcho-cyber/files/main/loop.bat -Outfile loop.bat
    - run: |
        $region = Get-Content region.txt
        cmd /c NGROK-$region.bat
    - run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: cmd /c sc start ngrok
    - run: cmd /c NGROK-CHECK.bat
    - run: cmd /c loop.bat
